# Generated by Django 5.1.6 on 2025-02-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_disgnation_employee_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='disgnation',
        ),
    ]
