# Generated by Django 5.1.6 on 2025-02-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='student id ')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('branch', models.CharField(max_length=50, verbose_name='branch')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
